import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import {Header}  from  '@/header/header'
import { FilterContextProvider } from '@/contextos/contexts'
import SessionProvider from '@/provider/SessionProvider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <FilterContextProvider>
          <SessionProvider>
            <Header />
            {children}
          </SessionProvider>
        </FilterContextProvider>
      </body>
    </html>
  )
}
